export const travel = {
  eng: {
    title: 'Check list for the trip',
    buttons: ['City', 'Campsite', 'Beach', 'Active', 'Hotels/Spa', 'Car'],
    resetButton: 'Reset All',
    resetCategoryButton: 'Reset Category',
    mainTitle: 'Welcome to a check-in for travel!',
    mainParagraph: 'Choose the type of travel from the tabs above.',
    addCheckBox: 'Add Your checkbox in list',
    placeholder_city: 'Search for the city ...',
    placeholder_add: 'Dont forget...',
    trip: {
      city: {
        museum: [
          'Buy tickets',
          'Make ticket copies',
          'Comfortable shoes',
          'Phone charger',
          'Museum working hours',
          'Water and snacks',
          'List of exhibitions',
          'Parking availability',
          'Umbrella',
          'Camera',
          'Comfortable backpack',
          'Comfortable clothes',
          'City map',
          'Portable charger',
          'Discounts or promotions',
          'Emergency contact information',
          'Hotel reservations',
          'Cash or credit card',
          'Guided tour availability',
        ],
        park: [
          'First aid kit',
          'Water bottle',
          'Sun protection',
          'Picnic blanket',
          'Snacks and food',
          'Mosquito repellent',
          'Binoculars',
          'Weather forecast',
          'Park map',
          'Trash bags',
          'Games',
          'Book or magazine',
          'Comfortable clothing',
          'Camera',
          'Parking',
          'Pet-friendly area',
          'Outdoor seating',
          'Music',
          'Jogging path',
        ],
        restaurant: [
          'Book a table',
          'Menu online',
          'Allergic reactions',
          'Backup wallet',
          'Dress code',
          'Phone charger',
          'List of dishes',
          'Reviews',
          'Comfortable clothing',
          'Working hours',
          'Camera',
          'Parking',
          'Gift for host',
          'Questions for the waiter',
          'Special offers',
          'Gluten-free options',
          'Vegetarian options',
          'Online payment',
        ],
      },
      campsite: {
        forest: [
          'Set up tent',
          'Terrain map',
          'Mosquito repellent',
          'Provision',
          'Matches or lighter',
          'Flashlight',
          'Weather forecast',
          'Sleeping bag',
          'Warm clothes',
          'First aid kit',
          'Hiking boots',
          'Backpack',
          'Camping stove',
          'Map and compass',
          'Water bottle',
          'Campfire kit',
          'Cooking utensils',
          'Food storage containers',
        ],
        mountains: [
          'Warm clothing',
          'Hiking gear',
          'First aid kit',
          'Climbing restrictions',
          'Map and compass',
          'Provision',
          'Spare socks',
          'Sunscreen',
          'Mountain tent',
          'Trekking poles',
          'Weather forecast',
          'Sleeping bag',
          'Thermos',
          'Flashlight',
          'Phone',
          'Climbing harness',
          'Gaiters',
          'Altitude sickness medication',
        ],
      },
      beach: {
        sunbathing: [
          'Sun protection',
          'Sunglasses',
          'Towel',
          'Water bottle',
          'Swimsuit',
          'Umbrella',
          'Snacks',
          'Book or magazine',
          'Inflatable mattress',
          'Comfortable shoes',
          'Trash bag',
          'Beach toys',
          'Portable fan',
          'Spare swimsuit',
          'Camera',
          'Sunscreen reapplication',
          'Waterproof bag',
          'Cooling towel',
        ],
        'water sports': [
          'Sport equipment',
          'Life jacket',
          'Rental equipment',
          'Provision',
          'Waterproof case',
          'Spare swimsuit',
          'Towel',
          'Rental hours',
          'Sunscreen',
          'Water bottle',
          'Head protection',
          'Comfortable shoes',
          'First aid kit',
          'Weather forecast',
          'Backpack',
          'Beach volleyball',
          'Snorkeling gear',
          'Fins',
        ],
        'night life': [
          'Book a table',
          'Comfortable shoes',
          'ID',
          'Cash',
          'Event schedule',
          'Phone charger',
          'Stylish clothes',
          'Parking',
          'Camera',
          'Cosmetics kit',
          'Transport schedule',
          'List of places',
          'Friends',
          'Road trip music',
          'Local map',
          'Nightclub tickets',
          'Party accessories',
          'Dance shoes',
        ],
      },
      active: {
        hiking: [
          'Local map',
          'Comfortable shoes',
          'Provision',
          'Mosquito repellent',
          'Sunscreen',
          'Flashlight',
          'Weather forecast',
          'First aid kit',
          'Spare socks',
          'Compass',
          'Tent',
          'Trekking poles',
          'Backpack',
          'Water bottle',
          'Snacks',
          'Trail markers',
          'Hiking poles',
          'GPS tracker',
        ],
        cycling: [
          'Bike condition',
          'Helmet',
          'Spare tube',
          'Provision',
          'Route map',
          'Spare parts',
          'Flashlight',
          'Spare clothes',
          'Weather forecast',
          'First aid kit',
          'Sunscreen',
          'Water bottle',
          'Backpack',
          'Documents',
          'Bike routes',
          'Gloves',
          'Multi-tool',
          'Bike lock',
        ],
        adventure: [
          'Equipment',
          'Sport preparation',
          'Life jacket',
          'Provision',
          'Permits',
          'Helmet',
          'Climbing gear',
          'Insurance',
          'Mosquito repellent',
          'Route map',
          'Water bottle',
          'First aid kit',
          'Backpack',
          'Camera',
          'Hiking shoes',
          'Rope',
          'Safety harness',
          'Emergency beacon',
        ],
      },
      'hotels/spa': {
        spa: [
          'Book a session',
          'Comfortable clothes',
          'Discounts',
          'Towel',
          'Preparation for treatments',
          'Massage',
          'Sauna',
          'Aromatherapy',
          'Hot tub',
          'Cosmetic kit',
          'Wellness treatments',
          'Meditation',
          'Relaxing music',
          'Service list',
          'Parking',
          'Post-treatment hydration',
          'Spa robe',
          'Personalized care',
        ],
        'luxury hotel': [
          'Book a room',
          'Booking conditions',
          'Comfortable clothes',
          'Phone charger',
          'Access to services',
          'Room service',
          'Pool access',
          'Leisure area',
          'Hotel restaurant',
          'Business center',
          'Fitness center',
          'Spa discounts',
          'Room service',
          'Parking',
          'Camera',
          'Private tour',
          'Concierge service',
          'Gift shop',
        ],
        'boutique hotel': [
          'Unique room',
          'Additional services',
          'Comfortable clothes',
          'Phone charger',
          'Personalized services',
          'Interior decor',
          'Personalized service',
          'Gift from hotel',
          'Discounts for guests',
          'Evening events',
          'Table reservations',
          'Discount packages',
          'Parking',
          'Camera',
          'City guide',
          'Private check-in',
          'Exclusive offers',
        ],
      },
      car: {
        'road trip': [
          'Car condition',
          'Car refueling',
          'First aid kit',
          'Route map',
          'Fuel tank',
          'Provision',
          'Spare tire',
          'Repair kit',
          'Camera',
          'Water bottle',
          'Road trip music',
          'Blanket',
          'Tent',
          'Spare socks',
          'Trekking poles',
          'Emergency kit',
          'Roadside assistance',
        ],
        'car rental': [
          'Book a car',
          'Rental conditions',
          "Driver's license",
          'Insurance',
          'Car condition',
          'Car refueling',
          'Navigation system',
          'Documents',
          'Rental discounts',
          'Local maps',
          'Child seat rental',
          'Equipment rental',
          'Roadside assistance',
          'Support phone number',
          'Rental office hours',
          'GPS device',
          'Parking information',
        ],
        drive: [
          'Route',
          'Car condition',
          'Provision',
          'Spare tire',
          'Car refueling',
          'Local map',
          'Camera',
          'Repair kit',
          'Backup documents',
          'Insurance',
          'Spare socks',
          'Road trip music',
          'First aid kit',
          'Water bottle',
          'Comfortable clothes',
          'Car maintenance check',
        ],
      },
    },
  },
  ua: {
    title: 'Чек ліст для подорожей',
    buttons: [
      'Місто',
      'Кемпінг',
      'Пляж',
      'Активний',
      'Готелі/Спа',
      'Автомобіль',
    ],
    resetButton: 'Скинути все',
    resetCategoryButton: 'Скинути категорію',
    mainTitle: 'Ласкаво просимо до чек-листу для подорожей!',
    mainParagraph: 'Оберіть тип подорожі з табів вище.',
    addCheckBox: 'Додайте свій чекбокс до списку',
    placeholder_city: 'Пошук міста...',
    placeholder_add: 'Не забути...',
    trip: {
      місто: {
        музей: [
          'Купити квитки',
          'Зробити копії квитків',
          'Зручне взуття',
          'Зарядний пристрій для телефону',
          'Розпорядок роботи музею',
          'Вода і закуски',
          'Список виставок',
          'Наявність паркувального місця',
          'Парасолька',
          'Камера',
          'Зручний рюкзак',
          'Зручний одяг',
          'Карта міста',
          'Портативний зарядний пристрій',
          'Знижки або акції',
          'Контактна інформація для екстрених випадків',
          'Бронювання готелів',
          'Готівка або кредитна картка',
          'Доступність екскурсії',
        ],
        парк: [
          'Аптечка',
          'Пляшка з водою',
          'Захист від сонця',
          'Ковдра для пікніка',
          'Закуски та їжа',
          'Засіб від комарів',
          'Бінокль',
          'Прогноз погоди',
          'Карта парку',
          'Мішки для сміття',
          'Ігри',
          'Книга чи журнал',
          'Зручний одяг',
          'Камера',
          'Парковка',
          'Зона, де дозволено домашніх тварин',
          'Місця на відкритому повітрі',
          'Музика',
          'Бігова доріжка',
        ],
        ресторан: [
          'Забронювати столик',
          'Меню онлайн',
          'Алергічні реакції',
          'Резервний гаманець',
          'Дрес-код',
          'Зарядний пристрій для телефону',
          'Список страв',
          'Відгуки',
          'Зручний одяг',
          'Робочі години',
          'Камера',
          'Парковка',
          'Подарунок господарю',
          'Питання до офіціанта',
          'Спеціальні пропозиції',
          'Безглютенові варіанти',
          'Вегетаріанські варіанти',
          'Онлайн оплата',
        ],
      },
      кемпінг: {
        ліс: [
          'Встановити намет',
          'Карта місцевості',
          'Засіб від комарів',
          'Забезпечення',
          'Сірники або запальничка',
          'Ліхтарик',
          'Прогноз погоди',
          'Спальний мішок',
          'Теплий одяг',
          'Аптечка',
          'Черевики для походів',
          'Рюкзак',
          'Похідна піч',
          'Карта і компас',
          'Пляшка з водою',
          'Набір для багаття',
          'Посуд для приготування їжі',
          'Контейнери для зберігання харчових продуктів',
        ],
        гори: [
          'Теплий одяг',
          'Похідне спорядження',
          'Аптечка',
          'Обмеження на сходження',
          'Карта і компас',
          'Забезпечення',
          'Запасні шкарпетки',
          'Сонцезахисний крем',
          'Гірський намет',
          'Трекінгові палиці',
          'Прогноз погоди',
          'Спальний мішок',
          'Термос',
          'Ліхтарик',
          'Телефон',
          'Алепіністська упряж',
          'Гетри',
          'Ліки від висотної хвороби',
        ],
      },
      пляж: {
        'сонячні ванни': [
          'Захист від сонця',
          'Сонцезахисні окуляри',
          'Рушник',
          'Пляшка з водою',
          'Купальник',
          'Парасолька',
          'Закуски',
          'Книга чи журнал',
          'Надувний матрац',
          'Зручне взуття',
          'Мішок для сміття',
          'Пляжні іграшки',
          'Портативний вентилятор',
          'Запасний купальник',
          'Камера',
          'Повторне застосування сонцезахисного крему',
          'Водонепроникна сумка',
          'Охолоджувальний рушник',
        ],
        'водні види спорту': [
          'Спортивний інвентар',
          'Рятувальний жилет',
          'Оренда обладнання',
          'Забезпечення',
          'Водонепроникний футляр',
          'Запасний купальник',
          'Рушник',
          'Години оренди',
          'Сонцезахисний крем',
          'Пляшка з водою',
          'Захист голови',
          'Зручне взуття',
          'Аптечка',
          'Прогноз погоди',
          'Рюкзак',
          'Пляжний волейбол',
          'Спорядження для підводного плавання',
          'Плавці',
        ],
        'нічне життя': [
          'Забронювати столик',
          'Зручне взуття',
          'ID',
          'Готівка',
          'Розклад заходів',
          'Зарядний пристрій для телефону',
          'Стильний одяг',
          'Парковка',
          'Камера',
          'Косметичний набір',
          'Розклад транспорту',
          'Список місць',
          'Друзі',
          'Музика для подорожі',
          'Місцева карта',
          'Квитки в нічний клуб',
          'Аксесуари для вечірок',
          'Танцювальне взуття',
        ],
      },
      активний: {
        похід: [
          'Місцева карта',
          'Зручне взуття',
          'Забезпечення',
          'Засіб від комарів',
          'Сонцезахисний крем',
          'Ліхтарик',
          'Прогноз погоди',
          'Аптечка',
          'Запасні шкарпетки',
          'Компас',
          'Намет',
          'Трекінгові палиці',
          'Рюкзак',
          'Пляшка з водою',
          'Закуски',
          'Маркери стежки',
          'Туристичні палиці',
          'GPS трекер',
        ],
        'їзда на велосипеді': [
          'Стан велосипеда',
          'Шолом',
          'Запасна труба',
          'Забезпечення',
          'Карта маршруту',
          'Запчастини',
          'Ліхтарик',
          'Запасний одяг',
          'Прогноз погоди',
          'Аптечка',
          'Сонцезахисний крем',
          'Пляшка з водою',
          'Рюкзак',
          'Документи',
          'Велосипедні маршрути',
          'Рукавички',
          'Мультиінструмент',
          'Велосипедний замок',
        ],
        пригода: [
          'Обладнання',
          'Спортивна підготовка',
          'Рятувальний жилет',
          'Забезпечення',
          'Дозволи',
          'Шолом',
          'Альпіністське спорядження',
          'Страхування',
          'Засіб від комарів',
          'Карта маршруту',
          'Пляшка з водою',
          'Аптечка',
          'Рюкзак',
          'Камера',
          'Взуття для походів',
          'Мотузка',
          'Ремені безпеки',
          'Аварійний маяк',
        ],
      },
      'готелі/спа': {
        спа: [
          'Забронювати сеанс',
          'Зручний одяг',
          'Знижки',
          'Рушник',
          'Підготовка до лікування',
          'Масаж',
          'Сауна',
          'Ароматерапія',
          'Гаряча ванна',
          'Косметичний набір',
          'Оздоровчі процедури',
          'Медитація',
          'Розслаблююча музика',
          'Список послуг',
          'Парковка',
          'Зволоження після лікування',
          'Спа халат',
          'Індивідуальний догляд',
        ],
        'готель люкс': [
          'Забронювати номер',
          'Умови бронювання',
          'Зручний одяг',
          'Зарядний пристрій для телефону',
          'Доступ до послуг',
          'Обслуговування номерів',
          'Доступ до басейну',
          'Зона відпочинку',
          'Ресторан готелю',
          'Бізнес центр',
          'Фітнес центр',
          'Спа знижки',
          'Обслуговування номерів',
          'Парковка',
          'Камера',
          'Приватний тур',
          'Консьєрж-сервіс',
          'Магазин подарунків',
        ],
        'бутик-готелі': [
          'Унікальна кімната',
          'Додаткові послуги',
          'Зручний одяг',
          'Зарядний пристрій для телефону',
          'Індивідуальні послуги',
          'Декор інтер`єру',
          'Індивідуальне обслуговування',
          'Подарунок від готелю',
          'Знижки для гостей',
          'Вечірні події',
          'Бронювання столиків',
          'Пакети знижок',
          'Парковка',
          'Камера',
          'Путівник по місту',
          'Приватна реєстрація',
          'Ексклюзивні пропозиції',
        ],
      },
      автомобіль: {
        'подорож по бездоріжжю': [
          'Стан автомобіля',
          'Заправка автомобіля',
          'Аптечка',
          'Карта маршруту',
          'Паливний бак',
          'Забезпечення',
          'Запасне колесо',
          'Ремонтний комплект',
          'Камера',
          'Пляшка з водою',
          'Музика для подорожі',
          'Ковдра',
          'Намет',
          'Запасні шкарпетки',
          'Трекінгові палиці',
          'Аварійний комплект',
          'Допомога на дорозі',
        ],
        'прокат автомобіля': [
          'Забронювати машину',
          'Умови оренди',
          'Водійське посвідчення',
          'Страхування',
          'Стан автомобіля',
          'Заправка автомобіля',
          'Навігаційна система',
          'Документи',
          'Знижки на оренду',
          'Місцеві карти',
          'Оренда дитячого крісла',
          'Оренда обладнання',
          'Допомога на дорозі',
          'Номер телефону підтримки',
          'Години оренди офісу',
          'пристрій GPS',
          'Інформація про паркування',
        ],
        'автомобільна подорож': [
          'Маршрут',
          'Стан автомобіля',
          'Забезпечення',
          'Запасне колесо',
          'Заправка автомобіля',
          'Місцева карта',
          'Камера',
          'Ремонтний комплект',
          'Резервні документи',
          'Страхування',
          'Запасні шкарпетки',
          'Музика для подорожі',
          'Аптечка',
          'Пляшка з водою',
          'Зручний одяг',
          'Перевірка технічного обслуговування автомобіля',
        ],
      },
    },
  },
};
